# Generated by Django 3.0.2 on 2020-01-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.RenameModel(
            old_name='Teas',
            new_name='Tea',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
