# Generated by Django 3.0.2 on 2020-01-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200109_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tea',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
