# Generated by Django 3.0.2 on 2020-01-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200109_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
